# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contacto', '0002_contactoproductos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactoproductos',
            old_name='mensaje',
            new_name='pedido',
        ),
    ]
