# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacto', '0003_auto_20170503_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactoproductos',
            name='cliente',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
