# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacto', '0004_contactoproductos_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactoproductos',
            name='cliente',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
