# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacto', '0005_auto_20170503_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactoproductos',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactoproductos',
            name='telefono',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
