# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacto', '0006_auto_20170503_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactoproductos',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
