# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('clave', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('medidas', models.CharField(max_length=40)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(upload_to='images/detalle/')),
                ('colores', models.ManyToManyField(to='Producto.Color')),
            ],
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('presentacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='Producto.Linea')),
            ],
        ),
        migrations.CreateModel(
            name='SubProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('caracteristica', models.CharField(max_length=300)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subproducto', to='Producto.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='detalleproducto',
            name='presentaciones',
            field=models.ManyToManyField(to='Producto.Presentacion'),
        ),
        migrations.AddField(
            model_name='detalleproducto',
            name='subproducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='Producto.Producto'),
        ),
    ]
