# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleproducto',
            name='clave',
            field=models.CharField(default='nombre', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subproducto',
            name='nombre',
            field=models.CharField(default='nombre', max_length=100),
            preserve_default=False,
        ),
    ]
