# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0003_auto_20170428_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproducto',
            name='colores',
            field=models.ManyToManyField(blank=True, null=True, to='Producto.Color'),
        ),
        migrations.AlterField(
            model_name='detalleproducto',
            name='presentaciones',
            field=models.ManyToManyField(blank=True, null=True, to='Producto.Presentacion'),
        ),
    ]
