# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0005_auto_20170428_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleproducto',
            name='especificaciones',
            field=models.CharField(default='especificacion', max_length=300),
            preserve_default=False,
        ),
    ]
