# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import modules.Producto.models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0007_auto_20170502_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproducto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=modules.Producto.models.image_producto_gral),
        ),
    ]
